### ISSUE TITLE
Missing readlink

### ISSUE THREAD

**Issue by alexandremottet** [JPyke3/arch-mbp-archiso#1]
I try to execute the script on a 2018 MacBook Pro but I get the following error :

```readlink: illegal option -- f```

Is this script is supposed to be executable on MacOs or do we need to already have an Arch installation to execute it ?

**Comment by JPyke3** [comment]
Hi there! Sorry about the delay in my response this one totally flew under my radar. This is designed for use on an existing Arch Install. If you would like to compile it on your mac I would recommend setting up a Virtual Machine running Arch and executing the script on that :)

**Comment by alexandremottet** [comment]
Thank you! I will try that
